### ISSUE TITLE
Adicionar um repositório de itens, com todos os itens já cadastrados

### ISSUE THREAD

**Issue by salomaoluiz** [salomaoluiz/BuyIt#84]
EU como usuário
QUERO ter uma lista com os itens já criados
PARA poder ao escanear ou começar a digitar o nome de algo já autopreencher

## Critério de aceite
- [ ] Devo validar o produto através do código de barras dele
- [ ] Caso o produto já exista, devo verificar os campos Nome, Marca, Preço e caso um desses seja diferente, devo mostrar a diferença e dar a opção para sobrescrever ou não

-----------------------------------------------------------------
# English Version
Add a items repository, with all items already created #84

I as a user
WANT have a list with the created items
TO when scan a barcode or start typing the name, the item auto complete

## Acceptance Criteria
- [ ] Should validate a product using your barcode
- [ ] If the product exists, should validate the fields name, brand and price and if anyone they are different, must show the difference and give a option to replace or not the item.

**Comment by alexakasanjeev** [comment]
Hi @salomaoluiz I'm looking at your code, and I want to know, where do you learn how to code like this in ReactNative, are you following any tutorials??

Olá salomaoluiz, estou olhando seu código e gostaria de saber, onde você aprende a codificar assim no ReactNative, está seguindo algum tutorial ??

**Comment by salomaoluiz** [comment]
Hi Sanjeev, I learn the basic of React Native using some courses in Udemy, and in a Brazilian platform called Alura. But the place when I grew up more faster it was in my work, in my day to day with another devs. If you have any throuble to understand the code, just send me a message, and i can try explain to you.

Oi Sanjeev, eu aprendi o basico do React Native usando alguns cursos na Udemy e em uma plataforma brasileira chamada Alura. Mas o local onde eu cresci mais rápido foi no meu trabalho, no meu dia a dia com outros desenvolvedores. Se você tiver qualquer problema para entender o código, me mande uma mensagem e posso tentar explicar para ti.

**Comment by alexakasanjeev** [comment]
Sure, thank you, I'm looking at your code, to learn, will ask if found something confusing

Can you explain this project, what it does, I tried translating the description into english, but didn't understand much about this project itself?

PS: I understand only english :)

**Comment by salomaoluiz** [comment]
Of course, here in Brazil we don't have much projects with a scalable structure, so, I created this project like a concept, to another brazilian devs learn more about redux, react navigation, hooks, how structure the folders/files and how integrate with firebase. The project is basically a app to organize a market list, creating lists and for any list created, create items, with the product name, brand, price, qtd, unit, and expiration date. In app also have a stock screen, when the user can place all items they has in your stock. This part is just beginning, in future I plan create a integration, where the user can remove items from stock and if the product is empty, they can create another list to next market purchase.
My english is not the best, but I can try translate the issues too, this way another devs and brazilian devs that don't speak english can use and collaborate with repo.

**Comment by alexakasanjeev** [comment]
Thanks for the explanation, and I understand the above English with no problem,

 basically it's sort of client app for content management system(CMS) if I'm correct

**Comment by salomaoluiz** [comment]
Yeah, it is like the app https://play.google.com/store/apps/details?id=com.l

**Comment by alexakasanjeev** [comment]
Hi @salomaoluiz Can you explain what [sonarqube](https://www.sonarqube.org/) is? and why are you using it in your project? what benefit it will provide?

Also you can enable [GitHub discussion](https://docs.github.com/en/discussions/quickstart), so that we can discuss there instead of typing in issues

**Comment by salomaoluiz** [comment]
Hi @alexakasanjeev, the Sonarqube is a platform to continuous inspection on code, I'm using the [Sonarcloud](https://sonarcloud.io/dashboard?id=salomaoluiz_BuyIt) as host, in every PR opened, is runned a scan in that PR, when it finish the scan, I can see if that code has code smell or common bugs, and if the test coverage is more than 97%, if anyone of quality gates has not been passed, the PR are be blocked while the author of PR has not been fix the code.

**Comment by alexakasanjeev** [comment]
Ok, can you tell me where can I learn the basics of it, if you know any good tutorial

**Comment by salomaoluiz** [comment]
sorry, but I don't have a good tutorial because another dev teached me the basic and for the advanced things I have been learned using the documentation. :/

**Comment by alexakasanjeev** [comment]
ok, no problem, you can write article if you ever get time, that way more people can find it helpful :)
